package Timer.TimeServerPackage;


/**
* Timer/TimeServerPackage/TimeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

abstract public class TimeHelper
{
  private static String  _id = "IDL:Timer/TimeServer/Time:1.0";

  public static void insert (org.omg.CORBA.Any a, Timer.TimeServerPackage.Time that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Timer.TimeServerPackage.Time extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "hours",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "minutes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[2] = new org.omg.CORBA.StructMember (
            "seconds",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Timer.TimeServerPackage.TimeHelper.id (), "Time", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Timer.TimeServerPackage.Time read (org.omg.CORBA.portable.InputStream istream)
  {
    Timer.TimeServerPackage.Time value = new Timer.TimeServerPackage.Time ();
    value.hours = istream.read_ulong ();
    value.minutes = istream.read_ulong ();
    value.seconds = istream.read_ulong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Timer.TimeServerPackage.Time value)
  {
    ostream.write_ulong (value.hours);
    ostream.write_ulong (value.minutes);
    ostream.write_ulong (value.seconds);
  }

}
