package Timer.TimeServerPackage;

/**
* Timer/TimeServerPackage/TimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

public final class TimeHolder implements org.omg.CORBA.portable.Streamable
{
  public Timer.TimeServerPackage.Time value = null;

  public TimeHolder ()
  {
  }

  public TimeHolder (Timer.TimeServerPackage.Time initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Timer.TimeServerPackage.TimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Timer.TimeServerPackage.TimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Timer.TimeServerPackage.TimeHelper.type ();
  }

}
