package Timer.TimeServerPackage;


/**
* Timer/TimeServerPackage/Time.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

public final class Time implements org.omg.CORBA.portable.IDLEntity
{
  public int hours = (int)0;
  public int minutes = (int)0;
  public int seconds = (int)0;

  public Time ()
  {
  } // ctor

  public Time (int _hours, int _minutes, int _seconds)
  {
    hours = _hours;
    minutes = _minutes;
    seconds = _seconds;
  } // ctor

} // class Time
