package CBCount;


/**
* CBCount/CounterClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* viernes 17 de mayo de 2019 03:47:34 PM CDT
*/

public interface CounterClient extends CounterClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CounterClient
