package Interfaces;


/**
* Interfaces/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* miércoles 12 de junio de 2019 04:44:16 AM CDT
*/

public interface ClienteOperations 
{
  String nombre ();
  void mostrarNotificacion (String mensaje, Interfaces.Cliente cliente);
} // interface ClienteOperations
