package Interfaces;


/**
* Interfaces/ClientePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* domingo 26 de mayo de 2019 03:23:54 PM CDT
*/

public abstract class ClientePOA extends org.omg.PortableServer.Servant
 implements Interfaces.ClienteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_nombre", new java.lang.Integer (0));
    _methods.put ("mostrarNotificacion", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Interfaces/Cliente/_get_nombre
       {
         String $result = null;
         $result = this.nombre ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Interfaces/Cliente/mostrarNotificacion
       {
         String mensaje = in.read_string ();
         Interfaces.Cliente cliente = Interfaces.ClienteHelper.read (in);
         this.mostrarNotificacion (mensaje, cliente);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Interfaces/Cliente:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Cliente _this() 
  {
    return ClienteHelper.narrow(
    super._this_object());
  }

  public Cliente _this(org.omg.CORBA.ORB orb) 
  {
    return ClienteHelper.narrow(
    super._this_object(orb));
  }


} // class ClientePOA
