package Interfaces;


/**
* Interfaces/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* domingo 26 de mayo de 2019 03:23:54 PM CDT
*/

public interface ClienteOperations 
{
  String nombre ();
  void mostrarNotificacion (String mensaje, Interfaces.Cliente cliente);
} // interface ClienteOperations
