package Interfaces;

/**
* Interfaces/ServidorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* miércoles 12 de junio de 2019 04:44:16 AM CDT
*/

public final class ServidorHolder implements org.omg.CORBA.portable.Streamable
{
  public Interfaces.Servidor value = null;

  public ServidorHolder ()
  {
  }

  public ServidorHolder (Interfaces.Servidor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Interfaces.ServidorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Interfaces.ServidorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Interfaces.ServidorHelper.type ();
  }

}
