package calc;

/**
* calc/enteroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 7 de mayo de 2019 02:13:57 PM CDT
*/

public final class enteroHolder implements org.omg.CORBA.portable.Streamable
{
  public calc.entero value = null;

  public enteroHolder ()
  {
  }

  public enteroHolder (calc.entero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calc.enteroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calc.enteroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calc.enteroHelper.type ();
  }

}
