package calc;


/**
* calc/enteroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 7 de mayo de 2019 02:13:57 PM CDT
*/

public interface enteroOperations 
{
  int suma (int a, int b);
  int resta (int a, int b);
  int multiplica (int a, int b);
  int divide (int a, int b, org.omg.CORBA.IntHolder resto) throws calc.NumeroIncorrecto;
} // interface enteroOperations
