package calc;


/**
* calc/NumeroIncorrecto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 7 de mayo de 2019 02:13:57 PM CDT
*/

public final class NumeroIncorrecto extends org.omg.CORBA.UserException
{

  public NumeroIncorrecto ()
  {
    super(NumeroIncorrectoHelper.id());
  } // ctor


  public NumeroIncorrecto (String $reason)
  {
    super(NumeroIncorrectoHelper.id() + "  " + $reason);
  } // ctor

} // class NumeroIncorrecto
