package calc;


/**
* calc/realPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 7 de mayo de 2019 02:13:57 PM CDT
*/

public abstract class realPOA extends org.omg.PortableServer.Servant
 implements calc.realOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("suma", new java.lang.Integer (0));
    _methods.put ("resta", new java.lang.Integer (1));
    _methods.put ("multiplica", new java.lang.Integer (2));
    _methods.put ("divide", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calc/real/suma
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.suma (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // calc/real/resta
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.resta (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // calc/real/multiplica
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.multiplica (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // calc/real/divide
       {
         try {
           double a = in.read_double ();
           double b = in.read_double ();
           double $result = (double)0;
           $result = this.divide (a, b);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (calc.NumeroIncorrecto $ex) {
           out = $rh.createExceptionReply ();
           calc.NumeroIncorrectoHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calc/real:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public real _this() 
  {
    return realHelper.narrow(
    super._this_object());
  }

  public real _this(org.omg.CORBA.ORB orb) 
  {
    return realHelper.narrow(
    super._this_object(orb));
  }


} // class realPOA
