package calc;


/**
* calc/realOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 7 de mayo de 2019 02:13:57 PM CDT
*/

public interface realOperations 
{
  double suma (double a, double b);
  double resta (double a, double b);
  double multiplica (double a, double b);
  double divide (double a, double b) throws calc.NumeroIncorrecto;
} // interface realOperations
