package calc;


/**
* calc/realHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 7 de mayo de 2019 02:13:57 PM CDT
*/

abstract public class realHelper
{
  private static String  _id = "IDL:calc/real:1.0";

  public static void insert (org.omg.CORBA.Any a, calc.real that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static calc.real extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (calc.realHelper.id (), "real");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static calc.real read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_realStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, calc.real value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static calc.real narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calc.real)
      return (calc.real)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calc._realStub stub = new calc._realStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static calc.real unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calc.real)
      return (calc.real)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calc._realStub stub = new calc._realStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
