package calc;

/**
* calc/realHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 7 de mayo de 2019 02:13:57 PM CDT
*/

public final class realHolder implements org.omg.CORBA.portable.Streamable
{
  public calc.real value = null;

  public realHolder ()
  {
  }

  public realHolder (calc.real initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calc.realHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calc.realHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calc.realHelper.type ();
  }

}
