package Timer.DateTimeServerPackage;


/**
* Timer/DateTimeServerPackage/DateTimeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

abstract public class DateTimeHelper
{
  private static String  _id = "IDL:Timer/DateTimeServer/DateTime:1.0";

  public static void insert (org.omg.CORBA.Any a, Timer.DateTimeServerPackage.DateTime that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Timer.DateTimeServerPackage.DateTime extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "day",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "month",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[2] = new org.omg.CORBA.StructMember (
            "year",
            _tcOf_members0,
            null);
          _tcOf_members0 = Timer.TimeServerPackage.TimeHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "hms",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Timer.DateTimeServerPackage.DateTimeHelper.id (), "DateTime", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Timer.DateTimeServerPackage.DateTime read (org.omg.CORBA.portable.InputStream istream)
  {
    Timer.DateTimeServerPackage.DateTime value = new Timer.DateTimeServerPackage.DateTime ();
    value.day = istream.read_ulong ();
    value.month = istream.read_ulong ();
    value.year = istream.read_ulong ();
    value.hms = Timer.TimeServerPackage.TimeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Timer.DateTimeServerPackage.DateTime value)
  {
    ostream.write_ulong (value.day);
    ostream.write_ulong (value.month);
    ostream.write_ulong (value.year);
    Timer.TimeServerPackage.TimeHelper.write (ostream, value.hms);
  }

}
