package Timer.DateTimeServerPackage;


/**
* Timer/DateTimeServerPackage/DateTime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

public final class DateTime implements org.omg.CORBA.portable.IDLEntity
{
  public int day = (int)0;
  public int month = (int)0;
  public int year = (int)0;
  public Timer.TimeServerPackage.Time hms = null;

  public DateTime ()
  {
  } // ctor

  public DateTime (int _day, int _month, int _year, Timer.TimeServerPackage.Time _hms)
  {
    day = _day;
    month = _month;
    year = _year;
    hms = _hms;
  } // ctor

} // class DateTime
