package Timer.DateTimeServerPackage;

/**
* Timer/DateTimeServerPackage/DateTimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

public final class DateTimeHolder implements org.omg.CORBA.portable.Streamable
{
  public Timer.DateTimeServerPackage.DateTime value = null;

  public DateTimeHolder ()
  {
  }

  public DateTimeHolder (Timer.DateTimeServerPackage.DateTime initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Timer.DateTimeServerPackage.DateTimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Timer.DateTimeServerPackage.DateTimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Timer.DateTimeServerPackage.DateTimeHelper.type ();
  }

}
