package ContactoApp;


/**
* ContactoApp/Contacto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contacto.idl
* miércoles 8 de mayo de 2019 03:10:17 PM CDT
*/

public final class Contacto implements org.omg.CORBA.portable.IDLEntity
{
  public String usuario = null;
  public String correo = null;
  public String tipo = null;

  public Contacto ()
  {
  } // ctor

  public Contacto (String _usuario, String _correo, String _tipo)
  {
    usuario = _usuario;
    correo = _correo;
    tipo = _tipo;
  } // ctor

} // class Contacto
