package ContactoApp;


/**
* ContactoApp/IContato.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contacto.idl
* miércoles 8 de mayo de 2019 03:10:18 PM CDT
*/

public interface IContato extends IContatoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IContato
