package ContactoApp;


/**
* ContactoApp/IContatoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contacto.idl
* miércoles 8 de mayo de 2019 03:10:18 PM CDT
*/

public interface IContatoOperations 
{
  void validar (String user, String pwd, ContactoApp.ContactoHolder contacto);
  void shutdown ();
} // interface IContatoOperations
