package Timer;


/**
* Timer/DateTimeServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

public interface DateTimeServerOperations  extends Timer.TimeServerOperations
{
  Timer.DateTimeServerPackage.DateTime get_date_time ();
} // interface DateTimeServerOperations
