package Timer;


/**
* Timer/TimeServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

public interface TimeServerOperations 
{
  Timer.TimeServerPackage.Time get_time ();
  void shutdown ();
} // interface TimeServerOperations
