/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumnosclienterest;

import alumnos.NewJerseyClient;
import java.awt.BorderLayout;
import java.awt.Button;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author k_ike
 */
public class Alumnos extends javax.swing.JFrame {

    /**
     * Creates new form Alumnos
     */
    public Alumnos() {
        initComponents();
        this.setTitle("ITVER");
        this.setLocationRelativeTo(null);
        comboPut.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroControl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBuscarGet = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaGet = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnEditarPut = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaPut = new javax.swing.JTextArea();
        comboPut = new javax.swing.JComboBox();
        txtPutNControl = new javax.swing.JTextField();
        txtPutNombre = new javax.swing.JTextField();
        txtPutCarrera = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarDelete = new javax.swing.JTextField();
        btnBuscarDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDelete = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TablePanelFocusGained(evt);
            }
        });
        TablePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePanelMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Registro de estudiantes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Numero de control:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Carrera:");

        btnEnviar.setBackground(new java.awt.Color(0, 0, 0));
        btnEnviar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Insertar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNumeroControl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(248, 248, 248))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        TablePanel.addTab("POST", jPanel1);

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número de control:");

        txtAreaGet.setEditable(false);
        txtAreaGet.setColumns(20);
        txtAreaGet.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtAreaGet.setRows(5);
        jScrollPane1.setViewportView(txtAreaGet);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarGet, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarGet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        TablePanel.addTab("GET", jPanel2);

        btnEditarPut.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarPut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEditarPut.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPut.setText("Actualizar");
        btnEditarPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPutActionPerformed(evt);
            }
        });

        txtAreaPut.setColumns(20);
        txtAreaPut.setRows(5);
        jScrollPane3.setViewportView(txtAreaPut);

        comboPut.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        comboPut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPut.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPutItemStateChanged(evt);
            }
        });
        comboPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPutActionPerformed(evt);
            }
        });

        txtPutNControl.setEditable(false);
        txtPutNControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPutNControlActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Número de control:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nombre: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Carrera:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboPut, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPutCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(txtPutNombre))
                                .addGap(28, 28, 28)
                                .addComponent(btnEditarPut))
                            .addComponent(txtPutNControl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPutNControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPutNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPut, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPutCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TablePanel.addTab("PUT", jPanel3);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Número de control:");

        txtBuscarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDeleteActionPerformed(evt);
            }
        });

        btnBuscarDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarDelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscarDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDelete.setText("Eliminar");
        btnBuscarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDeleteActionPerformed(evt);
            }
        });

        txtAreaDelete.setColumns(20);
        txtAreaDelete.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtAreaDelete.setRows(5);
        jScrollPane2.setViewportView(txtAreaDelete);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscarDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablePanel.addTab("DELETE", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablePanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablePanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (!txtNumeroControl.getText().isEmpty()) {
            if (!txtNombre.getText().isEmpty()) {
                if (!txtCarrera.getText().isEmpty()) {
                    NewJerseyClient cliente = new NewJerseyClient();
                    alumnos.Alumnos alumno = new alumnos.Alumnos();
                    alumno.setNumcontrol(txtNumeroControl.getText());
                    alumno.setNombre(txtNombre.getText());
                    alumno.setCarrera(txtCarrera.getText());
                    cliente.create_XML(alumno);
                    //System.out.println(cliente.find_XML(alumnos.Alumnos.class, txtNumeroControl.getText()));
                    alumnos.Alumnos alumnoSalida = cliente.find_XML(alumnos.Alumnos.class, txtNumeroControl.getText());
                    JOptionPane.showMessageDialog(this, "Número de control: " + alumno.getNumcontrol() + "\n"
                            + "Nombre: " + alumno.getNombre() + "\n"
                            + "Carrera: " + alumno.getCarrera() + "\n", "Alumno registrado", JOptionPane.INFORMATION_MESSAGE);
                    cliente.close();
                    txtNumeroControl.setText("");
                    txtNombre.setText("");
                    txtCarrera.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Falta la carrera", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Falta el nombre", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Falta el numero de control", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void TablePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TablePanelFocusGained

    }//GEN-LAST:event_TablePanelFocusGained

    private void TablePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePanelMouseClicked
        // TODO add your handling code here:
        comboPut.removeAllItems();
        String texto = "";
        NewJerseyClient cliente = new NewJerseyClient();
        alumnos.Alumnoss lista = cliente.findAll_XML(alumnos.Alumnoss.class);
        for (int i = 0; i < lista.getAlumnos().size(); i++) {
            texto += "Número de control: " + lista.getAlumnos().get(i).getNumcontrol()
                    + " Nombre: " + lista.getAlumnos().get(i).getNombre()
                    + " Carrera: " + lista.getAlumnos().get(i).getCarrera() + "\n\n";
            comboPut.addItem(lista.getAlumnos().get(i).getNumcontrol());
        }
        txtAreaGet.setText(texto);
        txtAreaDelete.setText(texto);
        txtAreaPut.setText(texto);
        cliente.close();
    }//GEN-LAST:event_TablePanelMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String texto = "";
        NewJerseyClient cliente = new NewJerseyClient();
        if (txtBuscarGet.getText().isEmpty()) {
            alumnos.Alumnoss lista = cliente.findAll_XML(alumnos.Alumnoss.class);
            for (int i = 0; i < lista.getAlumnos().size(); i++) {
                texto += "Número de control: " + lista.getAlumnos().get(i).getNumcontrol()
                        + " Nombre: " + lista.getAlumnos().get(i).getNombre()
                        + " Carrera: " + lista.getAlumnos().get(i).getCarrera() + "\n\n";
            }
            txtAreaGet.setText(texto);
        } else {
            alumnos.Alumnos alumno = cliente.find_XML(alumnos.Alumnos.class, txtBuscarGet.getText());
            if (alumno != null) {
                texto += "Número de control: " + alumno.getNumcontrol()
                        + " Nombre: " + alumno.getNombre()
                        + " Carrera: " + alumno.getCarrera();
                txtAreaGet.setText(texto);
            } else {
                JOptionPane.showMessageDialog(this, txtBuscarGet.getText(), "No encontrado", JOptionPane.ERROR_MESSAGE);
            }
        }
        cliente.close();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDeleteActionPerformed

    private void btnBuscarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDeleteActionPerformed
        // TODO add your handling code here:
        String texto = "";
        NewJerseyClient cliente = new NewJerseyClient();
        if (txtBuscarDelete.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error", "Ingrese un registro a eliminar", JOptionPane.ERROR_MESSAGE);
        } else {
            alumnos.Alumnos alumno = cliente.find_XML(alumnos.Alumnos.class, txtBuscarDelete.getText());
            if (alumno != null) {
                texto += "Número de control: " + alumno.getNumcontrol()
                        + " \nNombre: " + alumno.getNombre()
                        + " \nCarrera: " + alumno.getCarrera();
                cliente.remove(txtBuscarDelete.getText());
                JOptionPane.showMessageDialog(this, texto, "Eliminado", JOptionPane.INFORMATION_MESSAGE);
                texto="";
                alumnos.Alumnoss lista = cliente.findAll_XML(alumnos.Alumnoss.class);
                for (int i = 0; i < lista.getAlumnos().size(); i++) {
                    texto += "Número de control: " + lista.getAlumnos().get(i).getNumcontrol()
                            + " Nombre: " + lista.getAlumnos().get(i).getNombre()
                            + " Carrera: " + lista.getAlumnos().get(i).getCarrera() + "\n\n";
                }
                txtAreaDelete.setText(texto);
            } else {
                JOptionPane.showMessageDialog(this, txtBuscarDelete.getText(), "No encontrado", JOptionPane.ERROR_MESSAGE);
            }
        }
        cliente.close();
    }//GEN-LAST:event_btnBuscarDeleteActionPerformed

    private void btnEditarPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPutActionPerformed
        // TODO add your handling code here:
        String texto="";
        if (!txtPutNControl.getText().isEmpty()) {
            if (!txtPutNombre.getText().isEmpty()) {
                if (!txtPutCarrera.getText().isEmpty()) {
                    NewJerseyClient cliente = new NewJerseyClient();
                    alumnos.Alumnos alumno = new alumnos.Alumnos();
                    alumno.setNumcontrol(txtPutNControl.getText());
                    alumno.setNombre(txtPutNombre.getText());
                    alumno.setCarrera(txtPutCarrera.getText());
                    cliente.edit_XML(alumno, txtPutNControl.getText());
                    //System.out.println(cliente.find_XML(alumnos.Alumnos.class, txtNumeroControl.getText()));
                    alumnos.Alumnos alumnoSalida = cliente.find_XML(alumnos.Alumnos.class, txtPutNControl.getText());
                    JOptionPane.showMessageDialog(this, "Número de control: " + alumno.getNumcontrol() + "\n"
                            + "Nombre: " + alumno.getNombre() + "\n"
                            + "Carrera: " + alumno.getCarrera() + "\n", "Alumno actualizado", JOptionPane.INFORMATION_MESSAGE);
                     alumnos.Alumnoss lista = cliente.findAll_XML(alumnos.Alumnoss.class);
                for (int i = 0; i < lista.getAlumnos().size(); i++) {
                    texto += "Número de control: " + lista.getAlumnos().get(i).getNumcontrol()
                            + " Nombre: " + lista.getAlumnos().get(i).getNombre()
                            + " Carrera: " + lista.getAlumnos().get(i).getCarrera() + "\n\n";
                }
                txtAreaPut.setText(texto);
                    cliente.close();
                } else {
                    JOptionPane.showMessageDialog(this, "Falta la carrera", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Falta el nombre", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Falta el numero de control", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarPutActionPerformed

    private void comboPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPutActionPerformed
        // TODO add your handling code here:
         if(comboPut.getItemCount()!=0){
               NewJerseyClient cliente = new NewJerseyClient();
        alumnos.Alumnos alumno = cliente.find_XML(alumnos.Alumnos.class, comboPut.getSelectedItem().toString());
        txtPutNControl.setText(alumno.getNumcontrol());
        txtPutNombre.setText(alumno.getNombre());
        txtPutCarrera.setText(alumno.getCarrera());
        cliente.close();
        }
        
    }//GEN-LAST:event_comboPutActionPerformed

    private void txtPutNControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPutNControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPutNControlActionPerformed

    private void comboPutItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPutItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPutItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TablePanel;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarDelete;
    private javax.swing.JButton btnEditarPut;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox comboPut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAreaDelete;
    private javax.swing.JTextArea txtAreaGet;
    private javax.swing.JTextArea txtAreaPut;
    private javax.swing.JTextField txtBuscarDelete;
    private javax.swing.JTextField txtBuscarGet;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroControl;
    private javax.swing.JTextField txtPutCarrera;
    private javax.swing.JTextField txtPutNControl;
    private javax.swing.JTextField txtPutNombre;
    // End of variables declaration//GEN-END:variables
}
