package Corba;

/**
* Corba/ServidorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* sábado 8 de junio de 2019 02:38:43 PM CDT
*/

public final class ServidorHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.Servidor value = null;

  public ServidorHolder ()
  {
  }

  public ServidorHolder (Corba.Servidor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.ServidorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.ServidorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.ServidorHelper.type ();
  }

}
