package Corba;

/**
* Corba/UsuarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* sábado 8 de junio de 2019 02:38:43 PM CDT
*/

public final class UsuarioHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.Usuario value = null;

  public UsuarioHolder ()
  {
  }

  public UsuarioHolder (Corba.Usuario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.UsuarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.UsuarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.UsuarioHelper.type ();
  }

}
