package Corba;


/**
* Corba/UsuarioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* sábado 8 de junio de 2019 02:38:43 PM CDT
*/

public interface UsuarioOperations 
{
  String usuario ();
  void notificacion (String mostrar, Corba.Usuario usuario);
} // interface UsuarioOperations
