package FibonacciApp;


/**
* FibonacciApp/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* martes 7 de mayo de 2019 11:42:35 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
