package FibonacciApp;


/**
* FibonacciApp/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* martes 7 de mayo de 2019 11:42:35 PM CDT
*/

public interface FibonacciOperations 
{
  void Fibonacci (org.omg.CORBA.IntHolder x);
  void shutdown ();
} // interface FibonacciOperations
