package CBCount;


/**
* CBCount/CounterClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* jueves 16 de mayo de 2019 03:23:23 PM CDT
*/

public interface CounterClient extends CounterClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CounterClient
