package CBCount;


/**
* CBCount/CounterClientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* jueves 16 de mayo de 2019 03:23:23 PM CDT
*/

abstract public class CounterClientHelper
{
  private static String  _id = "IDL:CBCount/CounterClient:1.0";

  public static void insert (org.omg.CORBA.Any a, CBCount.CounterClient that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CBCount.CounterClient extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CBCount.CounterClientHelper.id (), "CounterClient");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CBCount.CounterClient read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CounterClientStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CBCount.CounterClient value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CBCount.CounterClient narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CBCount.CounterClient)
      return (CBCount.CounterClient)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CBCount._CounterClientStub stub = new CBCount._CounterClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CBCount.CounterClient unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CBCount.CounterClient)
      return (CBCount.CounterClient)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CBCount._CounterClientStub stub = new CBCount._CounterClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
