package CBCount;


/**
* CBCount/CounterClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* jueves 16 de mayo de 2019 03:23:23 PM CDT
*/

public interface CounterClientOperations 
{
  void update (int value);
} // interface CounterClientOperations
