package CBCount;


/**
* CBCount/CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* jueves 16 de mayo de 2019 03:23:23 PM CDT
*/

public interface CounterOperations 
{
  int value ();
  void inc ();
  void dec ();
  void add (CBCount.CounterClient cc);
  void remove (CBCount.CounterClient cc);
} // interface CounterOperations
