
import Corba.Servidor;
import Corba.ServidorHelper;
import Corba.Usuario;
import Corba.UsuarioHelper;
import itver.JerseyClient;
import java.awt.Component;
import java.awt.Image;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.omg.CORBA.ORB;
import org.omg.CORBA.ORBPackage.InvalidName;
import org.omg.CosNaming.NameComponent;
import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.NotFound;
import org.omg.PortableServer.POA;
import org.omg.PortableServer.POAHelper;
import org.omg.PortableServer.POAManagerPackage.AdapterInactive;
import org.omg.PortableServer.POAPackage.ServantNotActive;
import org.omg.PortableServer.POAPackage.WrongPolicy;

public class Run extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    String path;
    String nombre;
    ORB orb;
    org.omg.CORBA.Object objRef;
    NamingContextExt ncRef;
    Servidor servidor;
    POA rootpoa;
    objetoUsuario objUsuario;
    org.omg.CORBA.Object ref2;
    Usuario href2;
    NamingContextExt ncRef2;
    NameComponent path2[];
    Usuario usuario;
    JerseyClient jersey;
    usuarios alumno;

    public Run(String args[]) {
        initComponents();
        btnBImage.setEnabled(false);
        btnEImagen.setEnabled(false);
        btnSImagen.setEnabled(false);
        path = "";
        nombre = "";
        jersey = new JerseyClient();
        this.setLocationRelativeTo(null);
        this.setTitle("Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Salir();
            }
        });
        try {
            orb = ORB.init(args, null);
            objRef = orb.resolve_initial_references("NameService");
            ncRef = NamingContextExtHelper.narrow(objRef);
            servidor = ServidorHelper.narrow(ncRef.resolve_str("ABC"));

        } catch (Exception e) {
            System.out.println("Hello Client exception: " + e);
            e.printStackTrace();
        }

    }


    public void Salir() {
        servidor.eliminarUsuario(usuario);
        usuario = null;
        btnBImage.setEnabled(false);
        btnEImagen.setEnabled(false);
        btnSImagen.setEnabled(false);
        btnL.setEnabled(true);
        btnR.setEnabled(true);
    }


    public void Objeto(String nombre) throws InvalidName, AdapterInactive, ServantNotActive, WrongPolicy, org.omg.CosNaming.NamingContextPackage.InvalidName, org.omg.CosNaming.NamingContextPackage.InvalidName, NotFound, CannotProceed {
        //Creacion del objeto local 
        rootpoa = POAHelper.narrow(orb.resolve_initial_references("RootPOA"));
        rootpoa.the_POAManager().activate();

        objUsuario = new objetoUsuario(nombre);
        objUsuario.setORB(orb);

        // get object reference from the servant
        ref2 = rootpoa.servant_to_reference(objUsuario);
        href2 = UsuarioHelper.narrow(ref2);

        //org.omg.CORBA.Object objRef2 =  orb.resolve_initial_references("NameService");
        ncRef2 = NamingContextExtHelper.narrow(objRef);

        path2 = ncRef2.to_name("ABCD");
        ncRef2.rebind(path2, href2);

        usuario = UsuarioHelper.narrow(ncRef2.resolve_str("ABCD"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtUsuarioR = new javax.swing.JTextField();
        btnR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPassR = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtUsuarioL = new javax.swing.JTextField();
        btnL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPassL = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBImage = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnSImagen = new javax.swing.JButton();
        btnEImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 0, 0));
        Panel.setForeground(new java.awt.Color(0, 51, 51));
        Panel.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        txtUsuarioR.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtUsuarioR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioRActionPerformed(evt);
            }
        });

        btnR.setBackground(new java.awt.Color(255, 204, 204));
        btnR.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnR.setForeground(new java.awt.Color(153, 0, 153));
        btnR.setText("Registro");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Registrarse");

        txtPassR.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtPassR.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Contraseña:");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Nombre de usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPassR)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuarioR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioR, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtPassR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        Panel.addTab("Registro", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        txtUsuarioL.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtUsuarioL.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnL.setBackground(new java.awt.Color(255, 204, 204));
        btnL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnL.setForeground(new java.awt.Color(153, 0, 153));
        btnL.setText("Entrar");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar sesión");

        txtPassL.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtPassL.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Nombre de usuario:");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Contraseña:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(txtUsuarioL, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(txtPassL)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtUsuarioL, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(txtPassL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        Panel.addTab("Entrar", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        btnBImage.setBackground(new java.awt.Color(255, 204, 204));
        btnBImage.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBImage.setForeground(new java.awt.Color(153, 0, 153));
        btnBImage.setText("Buscar imagen");
        btnBImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBImageActionPerformed(evt);
            }
        });

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen.setForeground(new java.awt.Color(255, 255, 255));

        btnSImagen.setBackground(new java.awt.Color(255, 204, 204));
        btnSImagen.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSImagen.setForeground(new java.awt.Color(153, 0, 153));
        btnSImagen.setText("Subir imagen");
        btnSImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSImagenActionPerformed(evt);
            }
        });

        btnEImagen.setBackground(new java.awt.Color(255, 204, 204));
        btnEImagen.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEImagen.setForeground(new java.awt.Color(153, 0, 153));
        btnEImagen.setText("Eliminar imagen");
        btnEImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(192, 192, 192))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnBImage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        Panel.addTab("Imagenes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showDialog(null, "Seleccionar");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            ImageIcon imageIcon = new ImageIcon(chooser.getSelectedFile().getAbsolutePath()); // load the image to a imageIcon
            Image image = imageIcon.getImage(); // transform it 
            Image newimg = image.getScaledInstance(250, 200, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
            imageIcon = new ImageIcon(newimg);  // transform it back
            lblImagen.setIcon(imageIcon);
            path = chooser.getSelectedFile().getAbsolutePath();
            nombre = chooser.getSelectedFile().getName();
        }
    }//GEN-LAST:event_btnBImageActionPerformed

    private void btnSImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSImagenActionPerformed
        // TODO add your handling code here:
        if (path.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(btnSImagen, "No ha seleccionado una imagen", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (servidor.cargarImagen(nombre, path, usuario)) {
                lblImagen.setIcon(null);
                path = "";
                nombre = "";
            }
        }
    }//GEN-LAST:event_btnSImagenActionPerformed

    private void btnEImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEImagenActionPerformed
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(btnEImagen, "No ha seleccionado una imagen", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (servidor.borrarImagen("/" + nombre, usuario)) {
                lblImagen.setIcon(null);
                path = "";
                nombre = "";
            }
        }
    }//GEN-LAST:event_btnEImagenActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
                alumno = new usuarios();
                alumno = jersey.find_XML(usuarios.class, txtUsuarioL.getText());
                if (alumno == null) {
                    JOptionPane.showMessageDialog(null, "Usuario no registrado", "Error", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (alumno.password.equals(txtPassL.getText())) {
                        JOptionPane.showMessageDialog(null, "Exito", "Ok", JOptionPane.INFORMATION_MESSAGE);
                        try {
                            Objeto(alumno.getNombre());
                        } catch (InvalidName ex) {
                            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (AdapterInactive ex) {
                            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ServantNotActive ex) {
                            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (WrongPolicy ex) {
                            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (org.omg.CosNaming.NamingContextPackage.InvalidName ex) {
                            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (NotFound ex) {
                            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (CannotProceed ex) {
                            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        servidor.registrarUsuario(usuario);
                        txtUsuarioL.setText("");
                        txtPassL.setText("");
                        btnBImage.setEnabled(true);
                        btnEImagen.setEnabled(true);
                        btnSImagen.setEnabled(true);
                        btnL.setEnabled(false);
                        btnR.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Error", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
    }//GEN-LAST:event_btnLActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        // TODO add your handling code here:
                    alumno = new usuarios();
                    alumno = jersey.find_XML(usuarios.class, txtUsuarioR.getText());
                    if (alumno == null) {
                        alumno = new usuarios();
                        alumno.setNombre(txtUsuarioR.getText());
                        alumno.setPassword(txtPassR.getText());
                        jersey.create_XML(alumno);
                        alumno = jersey.find_XML(usuarios.class, txtUsuarioR.getText());
                        if (alumno == null) {
                            JOptionPane.showMessageDialog(null, "No se ha podido registrar", "Error", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "Exito, ahora inicia sesión", "Ok", JOptionPane.INFORMATION_MESSAGE);
                            txtUsuarioR.setText("");
                            txtPassR.setText("");
                            alumno = null;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El usuario ya existe", "Error", JOptionPane.INFORMATION_MESSAGE);
                    }
    }//GEN-LAST:event_btnRActionPerformed

    private void txtUsuarioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Run(args).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JButton btnBImage;
    private javax.swing.JButton btnEImagen;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnSImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPasswordField txtPassL;
    private javax.swing.JPasswordField txtPassR;
    private javax.swing.JTextField txtUsuarioL;
    private javax.swing.JTextField txtUsuarioR;
    // End of variables declaration//GEN-END:variables
}
