package ContactoApp;

/**
* ContactoApp/ContactoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contacto.idl
* miércoles 8 de mayo de 2019 03:10:17 PM CDT
*/

public final class ContactoHolder implements org.omg.CORBA.portable.Streamable
{
  public ContactoApp.Contacto value = null;

  public ContactoHolder ()
  {
  }

  public ContactoHolder (ContactoApp.Contacto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ContactoApp.ContactoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ContactoApp.ContactoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ContactoApp.ContactoHelper.type ();
  }

}
