package ContactoApp;


/**
* ContactoApp/IContatoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contacto.idl
* miércoles 8 de mayo de 2019 03:10:18 PM CDT
*/

abstract public class IContatoHelper
{
  private static String  _id = "IDL:ContactoApp/IContato:1.0";

  public static void insert (org.omg.CORBA.Any a, ContactoApp.IContato that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ContactoApp.IContato extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ContactoApp.IContatoHelper.id (), "IContato");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ContactoApp.IContato read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IContatoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ContactoApp.IContato value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ContactoApp.IContato narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ContactoApp.IContato)
      return (ContactoApp.IContato)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ContactoApp._IContatoStub stub = new ContactoApp._IContatoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ContactoApp.IContato unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ContactoApp.IContato)
      return (ContactoApp.IContato)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ContactoApp._IContatoStub stub = new ContactoApp._IContatoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
