package ContactoApp;

/**
* ContactoApp/IContatoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contacto.idl
* miércoles 8 de mayo de 2019 03:10:18 PM CDT
*/

public final class IContatoHolder implements org.omg.CORBA.portable.Streamable
{
  public ContactoApp.IContato value = null;

  public IContatoHolder ()
  {
  }

  public IContatoHolder (ContactoApp.IContato initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ContactoApp.IContatoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ContactoApp.IContatoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ContactoApp.IContatoHelper.type ();
  }

}
