package ContactoApp;


/**
* ContactoApp/IContatoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contacto.idl
* miércoles 8 de mayo de 2019 03:10:17 PM CDT
*/

public abstract class IContatoPOA extends org.omg.PortableServer.Servant
 implements ContactoApp.IContatoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("validar", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ContactoApp/IContato/validar
       {
         String user = in.read_string ();
         String pwd = in.read_string ();
         ContactoApp.ContactoHolder contacto = new ContactoApp.ContactoHolder ();
         this.validar (user, pwd, contacto);
         out = $rh.createReply();
         ContactoApp.ContactoHelper.write (out, contacto.value);
         break;
       }

       case 1:  // ContactoApp/IContato/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ContactoApp/IContato:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IContato _this() 
  {
    return IContatoHelper.narrow(
    super._this_object());
  }

  public IContato _this(org.omg.CORBA.ORB orb) 
  {
    return IContatoHelper.narrow(
    super._this_object(orb));
  }


} // class IContatoPOA
