package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* viernes 3 de mayo de 2019 10:30:39 PM CDT
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  int minus (int a, int b);
  int multiplyBy (int a, int b);
  double dividedBy (double a, double b);
  void shutdown ();
} // interface AdditionOperations
