package Interfaces;


/**
* Interfaces/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaces.idl
* miércoles 12 de junio de 2019 04:44:16 AM CDT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
