package FibonacciApp;

/**
* FibonacciApp/FibonacciHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* lunes 6 de mayo de 2019 10:35:20 PM CDT
*/

public final class FibonacciHolder implements org.omg.CORBA.portable.Streamable
{
  public FibonacciApp.Fibonacci value = null;

  public FibonacciHolder ()
  {
  }

  public FibonacciHolder (FibonacciApp.Fibonacci initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FibonacciApp.FibonacciHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FibonacciApp.FibonacciHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FibonacciApp.FibonacciHelper.type ();
  }

}
