package FibonacciApp;


/**
* FibonacciApp/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* lunes 6 de mayo de 2019 10:35:20 PM CDT
*/

public interface FibonacciOperations 
{
  int fibonacci (int x);
  void shutdown ();
} // interface FibonacciOperations
