package Timer;


/**
* Timer/DateTimeServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* jueves 9 de mayo de 2019 03:01:08 PM CDT
*/

public interface DateTimeServer extends DateTimeServerOperations, Timer.TimeServer, org.omg.CORBA.portable.IDLEntity 
{
} // interface DateTimeServer
