package FibonacciApp;


/**
* FibonacciApp/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* martes 7 de mayo de 2019 01:01:09 AM CDT
*/

public interface FibonacciOperations 
{
  int fibonacci (int x);
  void shutdown ();
} // interface FibonacciOperations
