package Fibonacci;


/**
* Fibonacci/fibonaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* martes 7 de mayo de 2019 03:30:01 PM CDT
*/

public interface fibonaOperations 
{
  void fibonacci (int f, org.omg.CORBA.IntHolder x);
  void shutdown ();
} // interface fibonaOperations
