package Fibonacci;

/**
* Fibonacci/fibonaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* martes 7 de mayo de 2019 03:30:01 PM CDT
*/

public final class fibonaHolder implements org.omg.CORBA.portable.Streamable
{
  public Fibonacci.fibona value = null;

  public fibonaHolder ()
  {
  }

  public fibonaHolder (Fibonacci.fibona initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Fibonacci.fibonaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Fibonacci.fibonaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Fibonacci.fibonaHelper.type ();
  }

}
