package Fibonacci;


/**
* Fibonacci/fibona.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* martes 7 de mayo de 2019 03:30:01 PM CDT
*/

public interface fibona extends fibonaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface fibona
