package Fibonacci;


/**
* Fibonacci/fibonaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fibonacci.idl
* martes 7 de mayo de 2019 03:30:01 PM CDT
*/

abstract public class fibonaHelper
{
  private static String  _id = "IDL:Fibonacci/fibona:1.0";

  public static void insert (org.omg.CORBA.Any a, Fibonacci.fibona that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Fibonacci.fibona extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Fibonacci.fibonaHelper.id (), "fibona");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Fibonacci.fibona read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_fibonaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Fibonacci.fibona value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Fibonacci.fibona narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fibonacci.fibona)
      return (Fibonacci.fibona)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Fibonacci._fibonaStub stub = new Fibonacci._fibonaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Fibonacci.fibona unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fibonacci.fibona)
      return (Fibonacci.fibona)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Fibonacci._fibonaStub stub = new Fibonacci._fibonaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
